"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { Activity, FileText, HeartPulse, History, LayoutDashboard, LogOut, Menu, Mic, Pill, Settings, ShieldAlert, Stethoscope, UserRound, X } from "lucide-react";
import { useState } from "react";
const items = [{ label: "Dashboard", href: "/dashboard", icon: LayoutDashboard }, { label: "Medicine scanner", href: "/medicine-scanner", icon: Pill }, { label: "Report analyzer", href: "/report-analyzer", icon: FileText }, { label: "Symptom checker", href: "/symptom-checker", icon: Stethoscope }, { label: "Voice assistant", href: "/voice-assistant", icon: Mic }, { label: "Health history", href: "/dashboard/history", icon: History }, { label: "Profile", href: "/dashboard/profile", icon: UserRound }, { label: "Settings", href: "/dashboard/settings", icon: Settings }];
export function Sidebar({ open, onClose }: { open: boolean; onClose: () => void }) { const pathname = usePathname(); const [collapsed, setCollapsed] = useState(false); const MenuBody = ({ mobile = false }: { mobile?: boolean }) => <><div className="flex items-center justify-between"><Link href="/dashboard" className="flex items-center gap-2 font-bold text-slate-950"><span className="grid size-10 place-items-center rounded-2xl bg-gradient-to-br from-sky-600 to-cyan-500 text-white shadow-lg shadow-sky-200"><HeartPulse className="size-5" /></span>{(!collapsed || mobile) && <span className="text-lg tracking-[-.04em]">med<span className="text-sky-600">ai</span></span>}</Link>{mobile ? <button aria-label="Close menu" className="grid size-9 place-items-center rounded-xl hover:bg-sky-50" onClick={onClose}><X className="size-5" /></button> : <button aria-label="Collapse sidebar" className="hidden rounded-xl p-2 text-slate-400 hover:bg-sky-50 lg:block" onClick={() => setCollapsed(!collapsed)}><Menu className="size-4" /></button>}</div><nav aria-label="Dashboard navigation" className="mt-8 space-y-1">{items.map(({ label, href, icon: Icon }) => <Link aria-current={pathname === href ? "page" : undefined} className={`group relative flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition-all ${pathname === href ? "bg-gradient-to-r from-sky-50 to-cyan-50 text-sky-700 shadow-sm" : "text-slate-600 hover:bg-sky-50 hover:text-sky-700"}`} href={href} key={label} onClick={onClose}><Icon className="size-4.5 shrink-0" />{(!collapsed || mobile) && <span>{label}</span>}{pathname === href && <motion.span layoutId={mobile ? "mobile-active" : "desktop-active"} className="absolute bottom-2 left-1 top-2 w-1 rounded-full bg-gradient-to-b from-sky-500 to-cyan-400" />}</Link>)}</nav><div className="mt-auto space-y-3"><div className={`rounded-2xl bg-gradient-to-br from-sky-600 to-cyan-500 p-4 text-white shadow-lg shadow-sky-200 ${collapsed && !mobile ? "hidden" : ""}`}><ShieldAlert className="size-5" /><p className="mt-3 text-sm font-bold">Emergency contacts</p><p className="mt-1 text-xs leading-5 text-sky-100">Keep important care contacts close.</p><Link className="mt-3 inline-block text-xs font-bold underline underline-offset-4" href="/dashboard/profile">Manage contacts</Link></div><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-500 transition hover:bg-rose-50 hover:text-rose-600"><LogOut className="size-4.5" />{(!collapsed || mobile) && "Logout"}</button></div></>;
return <><aside className={`sticky top-0 hidden h-screen shrink-0 flex-col border-r border-sky-100 bg-white/80 p-5 backdrop-blur-2xl transition-[width] duration-300 lg:flex ${collapsed ? "w-[88px]" : "w-72"}`}><MenuBody /></aside><AnimatePresence>{open && <><motion.button aria-label="Close sidebar" className="fixed inset-0 z-40 bg-slate-950/20 backdrop-blur-[1px] lg:hidden" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} /><motion.aside className="fixed inset-y-0 left-0 z-50 flex w-80 flex-col bg-white p-5 shadow-2xl lg:hidden" initial={{ x: -330 }} animate={{ x: 0 }} exit={{ x: -330 }} transition={{ type: "spring", stiffness: 260, damping: 26 }}><MenuBody mobile /></motion.aside></>}</AnimatePresence></>; }
