"use client";
import Link from "next/link";
import { motion } from "framer-motion";
import { HeartPulse, ShieldCheck, Sparkles } from "lucide-react";
import type { ReactNode } from "react";

export function AuthShell({ children, title, description }: { children: ReactNode; title: string; description: string }) {
  return <main className="relative grid min-h-screen overflow-hidden bg-slate-50 lg:grid-cols-[.9fr_1.1fr]"><div aria-hidden="true" className="absolute -left-28 top-20 size-80 rounded-full bg-sky-200/50 blur-3xl" /><aside className="relative hidden overflow-hidden bg-gradient-to-br from-sky-800 via-sky-700 to-cyan-600 p-12 text-white lg:flex lg:flex-col"><Link href="/" className="relative flex items-center gap-2"><span className="grid size-10 place-items-center rounded-xl bg-white/15"><HeartPulse className="size-5" /></span><span className="text-xl font-bold tracking-[-.04em]">medai</span></Link><div className="relative my-auto max-w-md"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-semibold"><Sparkles className="size-3.5" /> Personal health intelligence</span><h1 className="mt-6 text-5xl font-bold leading-[1.02] tracking-[-.055em]">A clearer way to care for yourself.</h1><p className="mt-6 text-lg leading-8 text-sky-100">Understand the information around your health in one calm, intelligent space.</p></div><div className="relative flex items-center gap-2 text-sm text-sky-100"><ShieldCheck className="size-4" /> Privacy-led by design</div><div aria-hidden="true" className="absolute -bottom-20 -right-20 size-80 rounded-full bg-cyan-300/25 blur-3xl" /></aside><section className="relative flex items-center justify-center px-5 py-12 sm:px-8"><Link href="/" className="absolute left-5 top-6 flex items-center gap-2 font-bold text-slate-950 lg:hidden"><span className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-sky-600 to-cyan-500 text-white"><HeartPulse className="size-5" /></span>medai</Link><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }} className="w-full max-w-md"><div className="rounded-3xl border border-white/80 bg-white/75 p-6 shadow-[0_20px_60px_rgba(14,116,144,.12)] backdrop-blur-xl sm:p-8"><h2 className="text-3xl font-bold tracking-[-.045em] text-slate-950">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p>{children}</div></motion.div></section></main>;
}

export const inputClass = "mt-1.5 w-full rounded-xl border border-sky-100 bg-white/80 px-3.5 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-sky-400 focus:ring-4 focus:ring-sky-100";
export const primaryButton = "inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-sky-600 to-cyan-600 px-4 py-3 text-sm font-semibold text-white shadow-[0_10px_22px_rgba(2,132,199,.22)] transition-transform hover:-translate-y-0.5 disabled:opacity-60";
